Update organizer page with 2024 team
hackbinghamton/hackbinghamton.github.io pull request #41
Opened 2024-09-16 04:19 UTC by Rubiginosa

2024-10-07 13:47 UTC, CodingKoopa requested changes
- Have you been able to test this locally?
- Also can now be updated for the new organizers :)

2024-10-07 13:47 UTC, CodingKoopa commented on organizers/index.html
> +    email: lucy@hackbu.org
this email no longer exists (though I think it does redirect to `admin@hackbu.org`) - you can use `kloerke1@binghamton.edu`

2024-10-07 13:50 UTC, CodingKoopa commented on organizers/index.html
>      email: cbingha@binghamton.edu
perhaps `admin@hackbu.org`

2024-10-08 21:49 UTC, CodingKoopa requested changes

2024-10-08 21:49 UTC, CodingKoopa commented on organizers/index.html
> -    pronouns: He/Him
If you're getting rid of the pronouns, you should also remove the relevant CSS: https://github.com/hackbinghamton/hackbinghamton.github.io/blob/d225137b52b3ba77d8c9ce45d16d29d498175a98/less/main.less#L529-L544

2024-10-26 21:25 UTC, Rubiginosa commented on organizers/index.html
> -    pronouns: He/Him
Collecting them's been kind of a pain in the past—I'll remove it for now and we can add them back once we're more on track.

2024-10-28 15:42 UTC, merged